### PR TITLE
feat: enum ProjectV2FieldType#TRACKED_BY

### PR DESCRIPTION
**Pull request by octokitbot**
I found new changes in GitHub's GraphQL Schema 👋🤖

I can't tell if the changes are fixes, features or breaking, you'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/openapi/blob/main/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

### CODE REVIEW

**Review by kfcampbell — APPROVED** [review]

**Comment by kfcampbell** [comment]
I'm unsure why the "test" check is hung in the expected state.

**Comment by wolfy1339** [comment]
It happens sometimes. :man_shrugging: No reason has been found yet
Pushing an empty commit should trigger the tests to run

**Comment by gr2m** [comment]
> It happens sometimes. 🤷‍♂️ No reason has been found yet
> Pushing an empty commit should trigger the tests to run

lately I haven't seen the `test` CI being triggered at all. I wonder if it has something to do that we use `pull_request_target` as trigger? It shouldn't make a difference, this is really weird

**Review by gr2m — APPROVED** [review]

**Comment by gr2m** [comment]
@kfcampbell I'd say you can merge PRs like this after you reviewed and updated the pull request title, no need for a 2nd review, unless you'd like a 2nd set of eyes

**Comment by kfcampbell** [comment]
Thank you both for the input!

**Pull request merged**
