### PR TITLE
feat: `addDiscussionPollVote()`, `addProjectDraftIssue()`, `addProjectNextItem()`, `createSponsorsTier()`, `deleteProjectNextItem()`, `dismissRepositoryVulnerabilityAlert()`, `followOrganization()`, `unfollowOrganization()`, `updateProjectDraftIssue()`, `updateProjectNext()`, `updateProjectNextItemField()`, `updatePullRequestBranch()`, `updateTeamsRepository()`. Mutations: `addDiscussionPollVote()`, `addProjectDraftIssue()`, `addProjectNextItem()`, `createSponsorsTier()`, `deleteProjectNextItem()`, `dismissRepositoryVulnerabilityAlert()`, `followOrganization()`, `unfollowOrganization()`, `updateProjectDraftIssue()`, `updateProjectNext()`, `updateProjectNextItemField()`, `updatePullRequestBranch()`, `updateTeamsRepository()`

### PR DESCRIPTION
**Pull request by octokitbot**
Release notes draft

### Features

- Lots  of additional query and mutation nodes for branch protections, e.g. `requiredStatusChecks`
- `.issues(filterBy: {milestoneNumber})`
- `{Organization,Repository,User}#recentProjects`
- `Discussion#poll`
- `DismissRepositoryVulnerabilityAlertInput#dismissReason`
- `Issue#{projectV2,projectsV2,projectV2Items}`,
- `Issue#stateReason`
- `Issue#trackedInIssues`
- `Issue#trackedIssues`
- `Issue#trackedIssuesCount`
- `Organization#{membersCanForkPrivateRepositories,projectV2,projectsV2,viewerIsFollowing}`
- `Organization#repositories({followRenames})`
- `ProjectV2#views({sortBy})`
- `ProjectV2#views`
- `PullRequest#{viewerCanEditFiles,viewerCanMergeAsAdmin}`
- `PullRequest#closingIssuesReferences({userLinkedOnly})`
- `Repository#{codeowners,squashPrTitleUsedAsDefault}`
- `Repository#discussionCategories({filterByAssignable})`
- `Repository#vulnerabilityAlerts({states})`
- `TreeEntry#lineCount`

### Mutations

- `addDiscussionPollVote()`
- `addProjectDraftIssue()`
- `addProjectV2DraftIssue()`
- `addProjectV2ItemById()`
- `createProjectV2()`
- `createSponsorsTier()`
- `deleteProjectV2Item()`
- `dismissRepositoryVulnerabilityAlert()`
- `followOrganization()`
- `unfollowOrganization()`
- `updateProjectDraftIssue()`
- `updateProjectV2()`
- `updateProjectV2Item()`
- `updateProjectV2ItemFieldValue()`
- `updateProjectV2ItemPosition()`
- `updatePullRequestBranch()`
- `updateTeamsRepository()`

### CODE REVIEW

**Review by gr2m — APPROVED** [review]

**Review by timrogers — COMMENTED** [review]
🚢 Lots of changes in here! Thanks for taking the time to go through it.

Should this be a minor version or a major version - or, in other words, did you see any breaking chanhes?

**Review by timrogers — APPROVED** [review]

**Comment by gr2m** [comment]
> Should this be a minor version or a major version - or, in other words, did you see any breaking changes?

I wouldn't treat breaking changes in the actual schema a breaking change for this module, it just reflects whatever GitHub's GraphQL schema is. So when a node gets removed, that's just a fix for this module.

A breaking change would be if any public APIs would change, e.g. if we rename any exports of the TypeScript module

**Comment by timrogers** [comment]
> I wouldn't treat breaking changes in the actual schema a breaking change for this module, it just reflects whatever GitHub's GraphQL schema is. So when a node gets removed, that's just a fix for this module.
> 
> 
> 
> A breaking change would be if any public APIs would change, e.g. if we rename any exports of the TypeScript module

I'm not 100% sure that I agree on this. It's a tricky case. 

To me, this situation feels the same as the other "types" packages. 

If you upgrade, your code that uses the exported types (e.g. `Repository`) could break - even if theoretically the change is a "fix" (because it just reflects the actual GraphQL schema). 

Whatever we decide, I think we should document our approach and stay consistent.

**Comment by timrogers** [comment]
If the GraphQL schema has changed, then your code would already be broken, even without upgrading this package. 

But I think a major version of this package.for a breaking schema change could be a useful signal to a developer that they may need to check the release notes and potentially upgrade their code to accommodate API changes.

**Pull request merged**
